project:
  type: website
  output-dir: docs

website:
  title: "Intro Stats"
  navbar:
    left:
      - about.qmd
      - href: index.qmd
        text: Home

format:
  html:
    theme: comos
    css: styles.css
    toc: true

